// <auto-generated />
using System;
using LoanApp.DAL.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoanApp.WebAPI.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    partial class LoanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoanApp.DAL.Model.CustomerLoanDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal?>("Balance");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal?>("EarlyRePaymentFee");

                    b.Property<decimal?>("Interest");

                    b.Property<long?>("LoanDetailsId");

                    b.Property<long>("LoanId");

                    b.Property<long>("LoanNumber");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<decimal?>("PayoutAmount");

                    b.HasKey("Id");

                    b.HasIndex("LoanDetailsId");

                    b.ToTable("CustomerLoanDetails");
                });

            modelBuilder.Entity("LoanApp.DAL.Model.LoanDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LoanDetails");
                });

            modelBuilder.Entity("LoanApp.DAL.Model.CustomerLoanDetails", b =>
                {
                    b.HasOne("LoanApp.DAL.Model.LoanDetails", "LoanDetails")
                        .WithMany("CustomerLoanDetails")
                        .HasForeignKey("LoanDetailsId");
                });
#pragma warning restore 612, 618
        }
    }
}
